# Define reusable key groups
key_groups:
  keys: &secret_keys
    - age:
        - age1yh7lqx5qj6u7wxed7sywd642thl7k32rr67th6n2d94adxc98gksnt4jeg
        - age10xqkavuu3uujfenfqphuf8xyxa325nwquv99jaxxrd64erha24lsg07fme
        - age1trvuu4ltrpuqvuxpyam4sygp0wkd0hzwr3t7ucra0k8a24zc55uqthwgze
        # Centric wsl
        - age1t6ph5yahupddrcx4qcqg68lcn7r5v25q8yr2f66h49htnwk9n3tsammrgy

creation_rules:
  - path_regex: 'secrets(/|\\)machines(/|\\)daf-laptop(/|\\).*'
    key_groups: *secret_keys

  - path_regex: 'secrets(/|\\)machines(/|\\)desktop-pc(/|\\).*'
    key_groups: *secret_keys

  - path_regex: 'secrets(/|\\)machines(/|\\)centric(/|\\).*'
    key_groups: *secret_keys

  - path_regex: 'secrets(/|\\)shared(/|\\).*'
    key_groups: *secret_keys
