# Generated by nixos-generate-config on the target machine.
# Run: nixos-generate-config --show-hardware-config > hosts/desktop-pc/hardware-configuration.nix
{ ... }:
{
  # Replace this file with the output of:
  #   nixos-generate-config --show-hardware-config
  # on the target machine.
}
